use std::env;
use std::fs::{read_to_string, write};
use std::path::PathBuf;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=user32_proxy.def");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let def_path = manifest_dir.join("user32_proxy.def");
    let def_abs = def_path.canonicalize().expect("user32_proxy.def not found");
    let contents = read_to_string(&def_abs).expect("Cannot read user32_proxy.def");

    let mut c_source = String::from("/* AUTO-GENERATED by build.rs */\n");
    let mut count = 0u32;
    for line in contents.lines() {
        let trimmed = line.trim();
        if trimmed.contains('=')
            && !trimmed.starts_with('[')
            && !trimmed.starts_with("LIBRARY")
            && !trimmed.starts_with("EXPORTS")
        {
            c_source.push_str(&format!(
                "#pragma comment(linker, \"/export:{}\")\n",
                trimmed
            ));
            count += 1;
        }
    }

    let c_path = manifest_dir.join("exports_pragma.c");
    write(&c_path, &c_source).expect("Failed to write exports_pragma.c");
    eprintln!(
        "build.rs: generated exports_pragma.c with {} /export: directives",
        count
    );

    let compiler = cc::Build::new().file(&c_path).get_compiler();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let obj_path = out_dir.join("exports_pragma.obj");

    let mut cmd = Command::new(compiler.path());
    cmd.args(compiler.args());
    cmd.args([
        "/c",
        &format!("/Fo{}", obj_path.display()),
        c_path.to_str().unwrap(),
    ]);

    eprintln!("build.rs: running {:?}", cmd);
    let status = cmd.status().expect("Failed to run cl.exe via cc");
    if !status.success() {
        panic!("cl.exe failed with status: {}", status);
    }

    eprintln!("build.rs: compiled {:?}", obj_path);

    println!("cargo:rustc-link-arg={}", obj_path.display());

    println!("cargo:rustc-link-lib=kernel32");
    println!("cargo:rustc-link-lib=user32");
    println!("cargo:rustc-link-lib=advapi32");
}
