[package]
name = "lumaforge-cdp-proxy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "user32"

[dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_SystemServices",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_Environment",
    "Win32_System_Diagnostics_Debug",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
] }
minhook = "0.8"
rand = "0.8"   

[build-dependencies]
cc = "1"

[profile.release]
opt-level = "s"
lto = false
strip = true